### ISSUE TITLE
is the proyect dead ?

### ISSUE THREAD

**Issue by alavaelian** [XelphLinux/xelph-iso#1]
i am looking for the website but it seems down, also can i configuro my dwm like xelph os

**Comment by Shinyzenith** [comment]
https://xelphlinux.com/
The project is not dead, I'm just not in the best of health of fix the broken ISO. I will get to it as soon as I can. 

Yes you can configure your dwm just like ours.

**Comment by alavaelian** [comment]
bro take care, can you tell me how are you have configured dwm

**Comment by Shinyzenith** [comment]
https://github.com/siduck/chadwm
