### ISSUE TITLE
Package manager error on install

### ISSUE THREAD

**Issue by mikebarbon** [XelphLinux/xelph-iso#2]
**Installation Failed**

Package Manager error
The package manager could not make changes to the installed system. The command

pacman -S --noconfirm linux linux-headers base-devel returned error code 1.

I selected no packages during install. Any idea how to fix?

**Comment by Shinyzenith** [comment]
I apologize for this, we're having an internal rewrite to an artix base along with wayland compositors which is taking some time. This bug will be gone once we get that finished,
